# Site settings
title: Kode Edwin
email: edwinlunando@gmail.com
description: "kehidupan, metode, cara kerja, dan kode"
username: edwinlunando
baseurl: ""
url: "http://edwinlunando.github.io"

# Build settings
markdown: kramdown
permalink: pretty
